# Generated by Django 5.2.6 on 2025-09-26 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(unique=True)),
                ('descuento', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficios', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('nro_documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto'), ('otro', 'Otro')], max_length=20, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimiento', models.DateField()),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.disciplina'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('referencia_externa', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.cuota')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('torneo', 'Torneo'), ('partido', 'Partido'), ('viaje', 'Viaje'), ('otro', 'Otro')], max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('requisito_pago', models.BooleanField(default=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='socios.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='socios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='socios.UsuarioRol', to='socios.rol'),
        ),
        migrations.CreateModel(
            name='SocioInfo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socios.usuario')),
                ('cuota_al_dia', models.BooleanField(default=True)),
                ('nivel_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.nivelsocio')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socioinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFamiliarIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.grupofamiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.usuario')),
            ],
            options={
                'unique_together': {('grupo_familiar', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.categoria')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.usuario')),
            ],
            options={
                'unique_together': {('categoria', 'entrenador')},
            },
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('recordatorio_min', models.IntegerField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.usuario')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('recordatorio_min__gte', 0)), name='recordatorio_no_negativo')],
            },
        ),
    ]
